### PR TITLE
SDL3/SDL_CreateSurfaceFrom: explain what pitch is

### PR DESCRIPTION
**Pull request by SDLWikiBot**
This edit was made by @Green-Sky.

Live page is here: https://wiki.libsdl.org/SDL3/SDL_CreateSurfaceFrom

If this user should be blocked from further edits, an admin should go to https://wiki.libsdl.org/Green-Sky/block
If this user should be trusted to make direct pushes to main, without a pull request, an admin should go to https://wiki.libsdl.org/Green-Sky/trust

### CODE REVIEW

**Comment by Green-Sky** [comment]
huh? was it wrong somehow?

**Comment by slouken** [comment]
No, I added a more technically correct explanation.

**Comment by slouken** [comment]
Thanks for the suggestion!

**Comment by Green-Sky** [comment]
Oh, I did not see that. Good then.
yea, every couple of years i look at it and ... don't know which way it works. :)

**Comment by icculus** [comment]
The pitch is allowed to be _larger_ than the size of the pixels, right? We should probably note that.

**Comment by icculus** [comment]
Also, maybe we should allow a pitch of 0 or -1 to say "there's no extra space, calculate this for me so I don't have to bother"

**Comment by slouken** [comment]
> The pitch is allowed to be _larger_ than the size of the pixels, right? We should probably note that.

Sure, feel free to update the wording. I don't necessarily want this to be a full blown tutorial on pitch - if you don't know what that is conceptually, you probably shouldn't be using this function. :)

**Comment by slouken** [comment]
> Also, maybe we should allow a pitch of 0 or -1 to say "there's no extra space, calculate this for me so I don't have to bother"

0 means "I'll fill this in later", but we should absolutely not have a "calculate this for me". If you don't know your source image pitch, you're basically guaranteed that this function will bite you in the butt.

**Pull request closed without merging**
