### PR TITLE
SDL3/SDL_EnumerateProperties: Fix small typo

### PR DESCRIPTION
**Pull request by SDLWikiBot**
This edit was made by @Ribiveer.

Live page is here: https://wiki.libsdl.org/SDL3/SDL_EnumerateProperties

If this user should be blocked from further edits, an admin should go to https://wiki.libsdl.org/Ribiveer/block
If this user should be trusted to make direct pushes to main, without a pull request, an admin should go to https://wiki.libsdl.org/Ribiveer/trust

### CODE REVIEW

**Comment by Ribiveer** [comment]
I don't know how to create a pull request with multiple commits from the wiki. It's not my intention to spam this repo with tiny commits!

**Comment by slouken** [comment]
No, please feel free to spam with multiple commits! The system is designed for us to be able to easily pick and choose what we accept, and it's no problem to see them individually.

**Comment by slouken** [comment]
I'm not sure your change is correct here. The enumerate function enumerates properties on a set of properties. I know that sounds redundant, but that's what it's doing.

**Comment by icculus** [comment]
"Enumerate the list of properties available from an SDL_PropertiesID"?

**Comment by slouken** [comment]
> "Enumerate the list of properties available from an SDL_PropertiesID"?

I like it!

**Comment by slouken** [comment]
Or "Enumerate the list of properties contained in an SDL_PropertiesID"?

**Comment by Ribiveer** [comment]
I hadn't been following this conversation, but I just came back to say that my change was indeed incorrect. So it's good that it's already been discussed.

**Comment by Ribiveer** [comment]
My proposed change would be "Enumerate the properties contained in a property set."

My two cents on the naming of `SDL_PropertiesID` and the functions containing the name "Properties", is that they are quite unintuitively named. When talking about "properties", it's ambiguous between multiple properties, a property set or multiple sets. Since they're called property sets elsewhere, I think renaming these to `SDL_CreatePropertySet` and `SDL_PropertySetID` respectively would help clear this up some more, and make the language surrounding it less confusing. This was also where I think my mistake came from when suggesting this change.

**Comment by slouken** [comment]
I went with your wording, thanks!
Can you open an SDL issue for confusion around SDL_PropertiesID? I'll add it to the ABI milestone for consideration.

**Comment by Ribiveer** [comment]
Done! It can be found here: https://github.com/libsdl-org/SDL/issues/10241

**Pull request closed without merging**
