### PR TITLE
SDL2/SDL_LockTexture: wording more precise

### PR DESCRIPTION
**Pull request by SDLWikiBot**
This edit was made by @u-an-i.

Live page is here: https://wiki.libsdl.org/SDL2/SDL_LockTexture

If this user should be blocked from further edits, an admin should go to https://wiki.libsdl.org/u-an-i/block
If this user should be trusted to make direct pushes to main, without a pull request, an admin should go to https://wiki.libsdl.org/u-an-i/trust

### CODE REVIEW

**Comment by u-an-i** [comment]
@slouken this and other merged PRs are not present anymore on live, apparently due to a sync `Sync SDL2 header -> wiki`: https://github.com/libsdl-org/sdlwiki/commits/main/SDL2/SDL_LockTexture.md https://github.com/libsdl-org/sdlwiki/commit/de76e6001984f66f00e6d38ba3586d3baf460b52  
  
Is this intended ?

**Comment by icculus** [comment]
> this and other merged PRs are not present anymore on live

I put this back in and it seemed to stay this time. Not sure what went wrong.

**Comment by u-an-i** [comment]
:)

This one from someone else also is missing: https://github.com/libsdl-org/sdlwiki/pull/423/files

I didn't check any further

**Comment by u-an-i** [comment]
@icculus i thank you! can you have a look at at least https://github.com/libsdl-org/sdlwiki/pull/423 ? That one was merged but I don't see it live either.

**Pull request merged**
