### PR TITLE
SDL2/SDL_GetDisplayBounds: Updated.

### PR DESCRIPTION
**Pull request by SDLWikiBot**
This edit was made by @bones-was-here.

Live page is here: https://wiki.libsdl.org/SDL2/SDL_GetDisplayBounds

If this user should be blocked from further edits, an admin should go to https://wiki.libsdl.org/bones-was-here/block
If this user should be trusted to make direct pushes to main, without a pull request, an admin should go to https://wiki.libsdl.org/bones-was-here/trust

### CODE REVIEW

**Comment by icculus** [comment]
This isn't correct (and if it's what's happening, it's a bug).

**Comment by bones-was-here** [comment]
If I put some debug prints in, on the test machine (Debian 12.2 SDL 2.26.5 NVIDIA Xorg) I get:  
`Display 0 pos: 1920 0 size: 1920 1080`

Which is consistent with `xrandr` output:
```
HDMI-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 531mm x 298mm
   1920x1080     60.00*+  59.94    50.00    60.05    60.00    50.04  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-0 disconnected (normal left inverted right x axis y axis)
DVI-D-0 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 509mm x 286mm panning 1920x1080+1920+0 tracking 1920x1080+0+0 border 0/0/0/0
   1920x1080     60.00 + 119.98*  109.95    99.93  
   1680x1050     59.95  
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94
```
The GPU detects the HDMI screen first but the DVI one is better so it's configured as primary and has the KDE taskbar on it.

**Comment by bones-was-here** [comment]
If you consider returning old data after hotplug events to be a bug, it seems to have been around for a while https://stackoverflow.com/questions/39810237/get-the-updated-screen-resolution-in-sdl2  

But having no idea if it's a bug or which program/driver/platform(s) the bug is in, and given that even if it's fixed many users will have the buggy versions for some time, I'm planning to just use a workaround that will behave correctly if the platform does, and hopefully fail safe if not:
```c
//		SDL_SetWindowPosition(window, SDL_WINDOWPOS_CENTERED_DISPLAY(displaywanted), SDL_WINDOWPOS_CENTERED_DISPLAY(displaywanted));
//		SDL_GetWindowPosition(window, &vid.xPos, &vid.yPos);

		/* bones_was_here BUG: after SDL_DISPLAYEVENT hotplug events,
		 * SDL_WINDOWPOS_CENTERED_DISPLAY(displaywanted) may place the window somewhere completely invisible.
		 * WORKAROUND: manual positioning seems safer: although SDL_GetDisplayBounds() may return outdated values,
		 * SDL_SetWindowPosition() always placed the window somewhere fully visible, even if it wasn't correct,
		 * when tested with SDL 2.26.5.
		 */
		SDL_Rect displaybounds;
		if (SDL_GetDisplayBounds(displaywanted, &displaybounds) < 0)
		{
			Con_Printf(CON_ERROR "Error getting bounds of display %i: \"%s\"\n", displaywanted, SDL_GetError());
			return;
		}
		vid.xPos = displaybounds.x + 0.5 * (displaybounds.w - vid.width);
		vid.yPos = displaybounds.y + 0.5 * (displaybounds.h - vid.height);
		SDL_SetWindowPosition(window, vid.xPos, vid.yPos);
```

**Comment by bones-was-here** [comment]
> The GPU detects the HDMI screen first

This was incorrect, mybad.  The DVI one is detected first and is primary by default.  
The HDMI one is (by default) assumed to be on the right, but it's physically placed on the left so it's configured to be on the left for correct mousing.  This can be done with xrandr:
```
xrandr --output DVI-D-0 --mode 1920x1080 --pos 0x0     --rate 120 --primary \
       --output HDMI-0  --mode 1920x1080 --pos -1920x0
```
But xrandr doesn't like the negative offset and converts it to the output posted above.

Same result though: the documentation isn't correct, 0,0 can belong to a displayindex other than 0, in this case 1.

**Comment by bones-was-here** [comment]
Is it an SDL bug, or a platform bug, or expected behavior, that after hotplug events `SDL_WINDOWPOS_CENTERED_DISPLAY(displaywanted)` behaves incorrectly and `SDL_GetDisplayBounds()` returns outdated information ?

**Comment by icculus** [comment]
I've opened an issue in SDL to look into this that links to this conversation:

https://github.com/libsdl-org/SDL/issues/9738

For now, I'm closing this PR, but if that turns out to be expected behavior, we'll add documentation then.

Thanks!

**Pull request closed without merging**
