### PR TITLE
SDL2/SDL_Rect: Setting the "x" and "h" fields of destrect to `0` to make the example more obvious that these fields are going to be ignored

### PR DESCRIPTION
**Pull request by SDLWikiBot**
This edit was made by @rempas.

Live page is here: https://wiki.libsdl.org/SDL2/SDL_Rect

If this user should be blocked from further edits, an admin should go to https://wiki.libsdl.org/rempas/block
If this user should be trusted to make direct pushes to main, without a pull request, an admin should go to https://wiki.libsdl.org/rempas/trust

### CODE REVIEW

**Comment by rempas** [comment]
Motivation about this wiki can be found in this [issue](https://github.com/libsdl-org/SDL/issues/8017) in the SDL repo.

**Comment by andrewbird** [comment]
Your PR title and commit says `x` and `h`, shouldn't that be `w` and `h`?

**Comment by rempas** [comment]
> Your PR title and commit says `x` and `h`, shouldn't that be `w` and `h`?

Yes, you are right! Sorry for the mistake!

**Comment by slouken** [comment]
Merged, thanks!

**Comment by rempas** [comment]
> Merged, thanks!

Thanks for caring about the community ;)

**Pull request merged**
