### PR TITLE
SDL3/SDL_EnumerateProperties: Add code example enumerating display properties

### PR DESCRIPTION
**Pull request by SDLWikiBot**
This edit was made by @mariobadr.

Live page is here: https://wiki.libsdl.org/SDL3/SDL_EnumerateProperties

If this user should be blocked from further edits, an admin should go to https://wiki.libsdl.org/mariobadr/block
If this user should be trusted to make direct pushes to main, without a pull request, an admin should go to https://wiki.libsdl.org/mariobadr/trust

WHETHER YOU MERGE OR REJECT THIS PULL REQUEST, DON'T FORGET TO DELETE THE BRANCH. Otherwise, mariobadr won't be able to start a new PR for this page.

### CODE REVIEW

**Comment by mariobadr** [comment]
On my system, compilation fails when using `%ld`. In this pull request, compilation fails because I used `%lld`. Is there a more portable way to print `Sint64`?

**Comment by mariobadr** [comment]
TIL about `SDL_PRIu64' (via: https://stackoverflow.com/a/8679). Could you please reject this pull request and I will re-edit the wiki with the appropriate format specifier? Thanks!

**Comment by icculus** [comment]
Just click edit again, it'll notice this pull request and let you update it.  :)

**Comment by icculus** [comment]
Ah, you got it already. Merging!

**Pull request merged**
