### PR TITLE
Add CI workflow

### PR DESCRIPTION
**Pull request by madebr**
Example output: https://github.com/madebr/sdlwiki/runs/7483454984

### CODE REVIEW

**Comment by icculus** [comment]
This is a very good idea, but I want to make sure this isn't going to upset the wiki software before I merge it.

**Comment by ericoporto** [comment]
Hey could this also push the artifacts so it's possible to download from the workflow and inspect then later? This would be useful to find out if something broke due to a commit here.

**Comment by madebr** [comment]
Added that possibility.
https://github.com/madebr/sdlwiki/actions/runs/5772747732

**Comment by ericoporto** [comment]
It works beautifully! Thank you!

**Comment by madebr** [comment]
> This is a very good idea, but I want to make sure this isn't going to upset the wiki software before I merge it.

It would only need to ignore dotfiles and/or dotdirectories.

**Comment by icculus** [comment]
Revisiting this, since I'm focusing on the wiki right now...the only thing this needs is to _also_ handle Markdown (.md) files, because we're moving away from MediaWiki (although some .mediawiki files are likely to live on). I'll fix up ignoring .github directories in ghwikipp itself.

**Comment by icculus** [comment]
> I'll fix up ignoring .github directories in ghwikipp itself.

Turns out I already did.  :)

https://github.com/libsdl-org/ghwikipp/blob/c602d5f8db92649517d3734c9f846002e08932ad/index.php#L1047-L1049

**Comment by madebr** [comment]
I'll fix this up, and look into building the examples.

**Comment by icculus** [comment]
Is this ready to merge at this point, or should I wait on it?

**Comment by madebr** [comment]
Let's commit this.
 I have a prototype for building the examples, but there are a lot of failures.
Something for a follow-up PR.
https://github.com/madebr/sdlwiki/actions/runs/8669314218/job/23775842552

**Comment by madebr** [comment]
My apologies about the 'f' commit :)

If you want ci to run for each commit/pr, you need to enable actions on this repo.

**Comment by icculus** [comment]
It's sdlwiki, half the commit messages are garbage.  :)

I'll enable actions shortly!

**Pull request merged**
