### PR TITLE
Build examples + Fix SDL3 examples

### PR DESCRIPTION
**Pull request by madebr**

### CODE REVIEW

**Comment by madebr** [comment]
The remaining failing SDL3 examples are android symbols, and documentation pages where the example is basically:
```
    ```c++
    You can add your code example here
    ```
````

**Comment by madebr** [comment]
> The remaining failing SDL3 examples are android symbols, and documentation pages where the example is basically:
> 
> ```
>     ```c++
>     You can add your code example here
>     ```
> ```
> 
> `SDL_GL_BindTexture` is also failing. Its example is probably way too complicated.

I removed those example blocks, and it turned out `SDL_GL_BindTexture` was removed from SDL3. :)

**Comment by icculus** [comment]
This is cool.   :)

**Comment by icculus** [comment]
Should the `#!/usr/bin/env python` in extract_example.py use `python3` instead? This is probably just needs to work on GitHub Actions, so not a big deal, but on Ubuntu 23.04, it fails if you try to run it with `python`, which is 2.7.18 in this case.

**Comment by madebr** [comment]
> Should the `#!/usr/bin/env python` in extract_example.py use `python3` instead? This is probably just needs to work on GitHub Actions, so not a big deal, but on Ubuntu 23.04, it fails if you try to run it with `python`, which is 2.7.18 in this case.

Yeah probably.
I assumed most distributions changed the `/usr/bin/python` symlink to python3 by now.

**Pull request merged**
