### PR TITLE
SDL3/CategoryKeyboard: Updated.

### PR DESCRIPTION
**Pull request by SDLWikiBot**
This edit was made by @edwardgushchin.

Live page is here: https://wiki.libsdl.org/SDL3/CategoryKeyboard

If this user should be blocked from further edits, an admin should go to https://wiki.libsdl.org/edwardgushchin/block
If this user should be trusted to make direct pushes to main, without a pull request, an admin should go to https://wiki.libsdl.org/edwardgushchin/trust

### CODE REVIEW

**Comment by edwardgushchin** [comment]
Removed keysym structure

**Comment by slouken** [comment]
@icculus, this should have happened automatically, right?

**Comment by icculus** [comment]
> this should have happened automatically, right?

It was, right after the page was removed, about 30 minutes ago:

https://github.com/libsdl-org/sdlwiki/commit/b114b3aa6ce200e029062392124269e23a99e208#diff-ed4849141283b957c032a8eb260d1034891241efa44cf5dd11746fc46c318c27L50

**Comment by icculus** [comment]
Not sure why GitHub thinks this can be merged without conflicts, though...

**Comment by slouken** [comment]
Ah, okay, cool.

**Pull request closed without merging**
