### PR TITLE
SDL3's SDL_GLContext has been changed into a struct typedef

### PR DESCRIPTION
**Pull request by madebr**

### CODE REVIEW

**Comment by slouken** [comment]
Before you commit this, maybe @icculus can see why this didn't automatically get picked up by the wiki script?

**Comment by icculus** [comment]
I was just wondering that myself. Please hold.

**Comment by icculus** [comment]
This was a bug in wikiheaders, fixed now in https://github.com/libsdl-org/SDL/commit/7c2329cd785897bd7ac1183e2db75ccd2ab299fe and wiki updated in 1eb27ea5449858c92defea8eaf3bba9ad84bdb17!

**Comment by madebr** [comment]
https://github.com/libsdl-org/sdlwiki/pull/556/commits/c9e27b0fa5eb5f3ca063f3c7662faa039e51ccb1 is still useful

**Comment by icculus** [comment]
Oh, I missed that, thanks...I'll put that in, too.

**Comment by icculus** [comment]
It's in!

**Comment by madebr** [comment]
It was cool to see the wiki site updated less then 10 seconds after pushing [this little documentation fix](https://github.com/libsdl-org/SDL/commit/a64960cfc0233479ea74ed33dacb39cd0d8aba6e).

**Pull request closed without merging**
